### ISSUE TITLE
Add survery questions to application

### ISSUE THREAD

**Issue by AllenYoungblood** [derekdotdev/YouthHomelessnessProject#1]
Add our survey question to the survey section

https://docs.google.com/document/d/14ZqP1r_k1Go3-uH0IzCNKUSnkB0lx3qT4EpXs9UQCVo/edit?usp=sharing

**Comment by derekdotdev** [comment]
James is working on an updated SQL script which will include create tables and questions.

**Comment by derekdotdev** [comment]
@jamesandrewpurvis is this issue ready to be closed out?

**Comment by jamesandrewpurvis** [comment]
> @jamesandrewpurvis is this issue ready to be closed out?

Yep, my commit with the zip code prompt contained the updated question script with create tables and all of the questions.
