### ISSUE TITLE
Update sidebar and footer on every page

### ISSUE THREAD

**Issue by derekdotdev** [derekdotdev/YouthHomelessnessProject#28]
Change footer on pages from "Copyright Virtusa 2020" / "Copyright Your Website 2020" to "Copyright Youth Homelessness Project 2022". Change sidebar from "Student Success" to "YHP" and increase font size.

**Comment by jamesandrewpurvis** [comment]
Hmm, should we stay with the name "StudentSuccess?" I guess it's something to talk about.
